version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Initialise Python venv, upgrade Pip, install Poetry"
          command: |
            python3.6 -m venv .venv
            python3.6 -m pip install --user --upgrade pip
            python3.6 -m pip install --user --upgrade poetry

      - run:
          name: "Install Python dependencies"
          command: |
            python3.6 -m poetry install

      - run:
          name: "Check Python code style (powered by Black)"
          command: |
            source .venv/bin/activate
            python -m black thingset --check

      - run:
          name: "Pytest"
          command: |
            source .venv/bin/activate
            python -m pytest --cov=thingset --cov-config=.coveragerc --cov-fail-under=90
